routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'PagesController@index')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {

    Route::resource('student', 'StudentController');
    Route::resource('teacher', 'TeacherController');
    Route::resource('employee', 'EmployeeController');
    Route::resource('major', 'MajorController');
    Route::resource('subjectgroup', 'SubjectgroupController', ['names' => 'subjectgroup']);
    Route::resource('groupsubject', 'GroupsubjectController');
    Route::resource('subject', 'SubjectController');
    Route::resource('majortype', 'MajortypeController');
    Route::resource('faculty', 'FacultyController');
    Route::resource('course', 'CourseController');
    Route::resource('classroom', 'ClassroomController');
    Route::resource('lecturer', 'LecturerController');
    Route::resource('educourse', 'EducourseController');

    Route::post('/find/district', 'ProviceController@district')->name('get_district');
    Route::post('/find/subdistrict', 'ProviceController@subdistrict')->name('get_subdistrict');
    Route::post('/find/poscode', 'ProviceController@poscode')->name('get_poscode');
    Route::post('/find/district1', 'ProviceController@district1')->name('get_district1');
    Route::post('/find/subdistrict1', 'ProviceController@subdistrict1')->name('get_subdistrict1');

//  Route::resource('purchase-order', 'PurchaseOrderController');
    //   Route::resource('department', 'DepartmentController');
    //   Route::resource('branch', 'BranchController');
    //   Route::resource('company', 'CompanyController');
});

// Demo routes
Route::get('/datatables', 'PagesController@datatables');
Route::get('/ktdatatables', 'PagesController@ktDatatables');
Route::get('/select2', 'PagesController@select2');
Route::get('/icons/custom-icons', 'PagesController@customIcons');
Route::get('/icons/flaticon', 'PagesController@flaticon');
Route::get('/icons/fontawesome', 'PagesController@fontawesome');
Route::get('/icons/lineawesome', 'PagesController@lineawesome');
Route::get('/icons/socicons', 'PagesController@socicons');
Route::get('/icons/svg', 'PagesController@svg');

// Quick search dummy route to display html elements in search dropdown (header search)
Route::get('/quick-search', 'PagesController@quickSearch')->name('quick-search');

Auth::routes();
Route::get('/home', 'PagesController@index')->name('home');
// Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/MajorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\TbMajor;
use App\TbMajorType;

use function PHPSTORM_META\type;

class MajorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $page_title = 'สาขาวิชา';
        $major = TbMajor::get();
        return view('pages.major.index', compact('page_title','major'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $page_title = 'เพิ่มสาขาวิชา';
        $majortype = TbMajorType::all();
        return view('pages.Major.create', compact('page_title','majortype'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request);
        $requestData = $request->all();
        TbMajor::create($requestData);
        return redirect()->route('major.index')->with('success', 'เพิ่มข้อมูลสำเร็จ');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $page_title = 'แก้ใขข้อมูลสาขา';
        $major = TbMajor::find($id);
        $majortype = TbMajorType::all();
        return view('pages.Major.edit',compact('page_title','major','majortype','id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $major = TbMajor::find($id);
        $major->major_id = $request->get('major_id');
        $major->major_name = $request->get('major_name');
        $major->major = $request->get('major');
        $major->major_type_id = $request->get('major_type_id');
        $major->save();
        return redirect()->route('major.index')->with('success','แก้ใขเรียบร้อย');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $major = TbMajor::find($id);
        $major->delete();
        return redirect()->route('major.index')->with('success','ลบข้อมูลเรียบร้อย');
    }
}

resources/views/pages/Major/create.blade.php
{{-- Extends layout --}}
@extends('layout.default')

{{-- Content --}}
@section('content')
<form class="form" id="kt_form" action="{{ route('major.store') }}" method="POST" enctype="multipart/form-data">
<div class="card card-custom card-sticky" id="kt_page_sticky_card">
  <!--begin::Form-->
  <div class="card-header">
    <div class="card-title">
      <h3 class="card-label">
        เพิ่มสาขาวิชา<i class="mr-2"></i>
      </h3>
    </div>
    <div class="card-toolbar">
      <a href="{{route('major.index')}}" class="btn btn-light-primary font-weight-bolder mr-2">
        <i class="ki ki-long-arrow-back icon-sm"></i>
        กลับ
      </a>
      <div class="btn-group">
        <button type="submit" id="save_form" class="btn btn-primary font-weight-bolder">
          <i class="ki ki-check icon-sm"></i>
          เพิ่มข้อมูล
        </button>
      </div>
    </div>
  </div>
  <div class="card-body">
      @csrf
      <div class="row">
        <div class="col-xl-2"></div>
        <div class="col-xl-8">
          @if ($errors->any())
          <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
              @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
              @endforeach
            </ul>
          </div>
          @endif

          <div class="my-5">
            <h3 class=" text-dark font-weight-bold mb-10">สาขาวิชา :</h3>
            <div class="form-group row">
                <label class="col-3">รหัสสาขา</label>
                <div class="col-9">
                  <input class="form-control form-control-solid" name="major_id" type="text" value="" />
                </div>
              </div>
            <div class="form-group row">
              <label class="col-3">ชื่อสาขา</label>
              <div class="col-9">
                <input class="form-control form-control-solid" name="major_name" type="text" value="" />
              </div>
            </div>

            <div class="form-group row">
                <label class="col-3">ระดับการศึกษา</label>
                <div class="col-9">
                    <select class="form-control form-control" name="major">
                        <option value="">ระดับการศึกษา</option>
                        <option value="ปวช">ปวช</option>
                        <option value="ปวส">ปวส</option>
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-3">ประเภทวิชา</label>
                <div class="col-9">
                    <select class="form-control form-control" name="major_type_id">
                        <option value="">ประเภทวิชา</option>
                        @foreach($majortype as $row )
			                <option value="{{$row->major_type_id}}">{{$row->major_type_name}}</option>
		                @endforeach
                    </select>
                </div>
            </div>


          </div>

          <div class="separator separator-dashed my-10"></div>

        </div>
        <div class="col-xl-2"></div>
        <!--end::Form-->
    </form>
  </div>


</div>

</div>


@endsection

{{-- Scripts Section --}}
@section('scripts')
<script>
  $(document).ready(function() {
    $('#save_form').on('click', function() {
      // window.location = "/purchase-order";
      // $('#kt_form').submit();
    });

    FormValidation.formValidation(
      document.getElementById('kt_form'), {
        fields: {
            major_id: {
            validators: {
              notEmpty: {
                message: 'กรอกรหัสสาขา'
              },
              stringLength: {
                max: 2,
                message: 'รหัสสาขาไม่เกิน 2 ตัว'
              }
            }
          },

          major_name: {
            validators: {
              notEmpty: {
                message: 'กรอกชื่อสาขา'
              }
            }
          },

          major: {
            validators: {
              notEmpty: {
                message: 'เลือกระดับการศึกษา'
              }
            }
          },

          major_type_id: {
            validators: {
              notEmpty: {
                message: 'เลือกประเภทการศึกษา'
              }
            }
          },


        },

        plugins: {
          trigger: new FormValidation.plugins.Trigger(),
          // Bootstrap Framework Integration
          bootstrap: new FormValidation.plugins.Bootstrap(),
          // Validate fields when clicking the Submit button
          submitButton: new FormValidation.plugins.SubmitButton(),
          // Submit the form when all fields are valid
          defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
        }
      }
    );
  });
</script>
@endsection

resources/views/pages/Major/edit.blade.php
{{-- Extends layout --}}
@extends('layout.default')

{{-- Content --}}
@section('content')
<form class="form" id="kt_form" action="{{action('MajorController@update',$id)}}" method="POST" enctype="multipart/form-data">
<div class="card card-custom card-sticky" id="kt_page_sticky_card">
  <!--begin::Form-->
  <div class="card-header">
    <div class="card-title">
      <h3 class="card-label">
        เพิ่มสาขาวิชา<i class="mr-2"></i>
      </h3>
    </div>
    <div class="card-toolbar">
      <a href="{{route('major.index')}}" class="btn btn-light-primary font-weight-bolder mr-2">
        <i class="ki ki-long-arrow-back icon-sm"></i>
        กลับ
      </a>
      <div class="btn-group">
        <button type="submit" id="save_form" class="btn btn-primary font-weight-bolder">
          <i class="ki ki-check icon-sm"></i>
          แก้ใขข้อมูล
        </button>
      </div>
    </div>
  </div>
  <div class="card-body">
      @csrf
      <div class="row">
        <div class="col-xl-2"></div>
        <div class="col-xl-8">
          @if ($errors->any())
          <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
              @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
              @endforeach
            </ul>
          </div>
          @endif

          <div class="my-5">
            <h3 class=" text-dark font-weight-bold mb-10">สาขาวิชา :</h3>
            <div class="form-group row">
                <label class="col-3">รหัสสาขา</label>
                <div class="col-9">
                  <input class="form-control form-control-solid" name="major_id" type="text" value="{{$major->major_id}}" />
                </div>
              </div>
            <div class="form-group row">
              <label class="col-3">ชื่อสาขา</label>
              <div class="col-9">
                <input class="form-control form-control-solid" name="major_name" type="text" value="{{$major->major_name}}" />
              </div>
            </div>

            <div class="form-group row">
                <label class="col-3">ระดับการศึกษา</label>
                <div class="col-9">
                    <select class="form-control form-control" name="major">
                        <option value="{{$major->major}}">{{$major->major}}</option>
                        <option value="ปวช">ปวช</option>
                        <option value="ปวส">ปวส</option>
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-3">ประเภทวิชา</label>
                <div class="col-9">
                    <select class="form-control form-control" name="major_type_id">
                        <option value="{{$major->majortype->major_type_id}}"> {{$major->majortype->major_type_name}}</option>
                        @foreach($majortype as $row )
			                <option value="{{$row->major_type_id}}">{{$row->major_type_name }}</option>
		                @endforeach
                    </select>
                </div>
            </div>

          </div>


          <input type="hidden" name="_method" value="PATCH"/>
          <div class="separator separator-dashed my-10"></div>

        </div>
        <div class="col-xl-2"></div>
        <!--end::Form-->
    </form>
  </div>


</div>

</div>


@endsection

{{-- Scripts Section --}}
@section('scripts')
<script>
  $(document).ready(function() {
    $('#save_form').on('click', function() {
      // window.location = "/purchase-order";
      // $('#kt_form').submit();
    });

    FormValidation.formValidation(
      document.getElementById('kt_form'), {
        fields: {
            major_id: {
            validators: {
              notEmpty: {
                message: 'กรอกรหัสสาขา'
              },
              stringLength: {
                max: 2,
                message: 'รหัสไม่เกิน 2 ตัว'
              }
            }
          },

          major_name: {
            validators: {
              notEmpty: {
                message: 'กรอกชื่อสาขา'
              }
            }
          },

          major_type_id: {
            validators: {
              notEmpty: {
                message: 'เลือกประเภทการศึกษา'
              }
            }
          },


        },

        plugins: {
          trigger: new FormValidation.plugins.Trigger(),
          // Bootstrap Framework Integration
          bootstrap: new FormValidation.plugins.Bootstrap(),
          // Validate fields when clicking the Submit button
          submitButton: new FormValidation.plugins.SubmitButton(),
          // Submit the form when all fields are valid
          defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
        }
      }
    );
  });
</script>
@endsection

resources/views/pages/Major/index.blade.php
{{-- Extends layout --}}
@extends('layout.default')

{{-- Content --}}
@section('content')

<div class="card card-custom">
  <div class="card-header flex-wrap border-0 pt-6 pb-0">
    <div class="card-title">
      <h2 class="card-label">ข้อมูลสาขา
        <div class="text-muted pt-2 font-size-sm"></div>
      </h2>
    </div>
    <div class="card-toolbar">
      <!--begin::Button-->
      <a href="{{route('major.create')}}" class="btn btn-primary font-weight-bolder">
        <span class="svg-icon svg-icon-md">
          <!--begin::Svg Icon | path:assets/media/svg/icons/Design/Flatten.svg-->
          <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
              <rect x="0" y="0" width="24" height="24" />
              <circle fill="#000000" cx="9" cy="15" r="6" />
              <path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3" />
            </g>
          </svg>
          <!--end::Svg Icon-->
        </span>เพิ่มชื่อสาขา</a>
      <!--end::Button-->
    </div>
  </div>
  <div class="card-body">
    <!--begin: Search Form-->
    <!--begin::Search Form-->
    <div class="mb-7">
      <div class="row align-items-center">
        <div class="col-lg-9 col-xl-8">
          <div class="row align-items-center">
            <div class="col-md-4 my-2 my-md-0">
              <div class="input-icon">
                <input type="text" class="form-control" placeholder="Search..." id="kt_datatable_search_query" />
                <span>
                  <i class="flaticon2-search-1 text-muted"></i>
                </span>
              </div>
            </div>
            <div class="col-md-4 my-2 my-md-0">
              <div class="d-flex align-items-center">
                <label class="mr-3 mb-0 d-none d-md-block">Status:</label>
                <select class="form-control" id="kt_datatable_search_status">
                  <option value="">All</option>
                  <option value="1">Active</option>
                  <option value="2">Inactive</option>
                </select>
              </div>
            </div>

          </div>
        </div>
        <div class="col-lg-3 col-xl-4 mt-5 mt-lg-0">
          <a href="#" class="btn btn-light-primary px-6 font-weight-bold">Search</a>
        </div>
      </div>
    </div>
    <!--end::Search Form-->
    <!--end: Search Form-->
    <!--begin: Datatable-->
    @if ($message = Session::get('success'))
    <div class="alert alert-success">
      <p>{{ $message }}</p>
    </div>
    @endif
    <table class="datatable datatable-bordered datatable-head-custom" id="kt_datatable">
      <thead>
        <tr>
            <th title="Field #1">รหัสสาขา</th>
            <th title="Field #2">ชื่อสาขา</th>
            <th title="Field #3">ระดับการศึกษา</th>
            <th title="Field #4">ประเภทวิชา</th>
            <th title="Field #5">Edit</th>
            <th title="Field #6">Delete</th>
            <th title="Field #7"></th>
        </tr>
      </thead>
      <tbody>
        @foreach ($major as $row)
        <tr>
            <td>{{$row->major_id}}</td>
            <td>{{$row->major_name}}</td>
            <td>{{$row->major}}</td>
            <td>{{$row->majortype->major_type_name}}</td>

        <td>
            <a href="{{action('MajorController@edit',$row->major_id)}}" class="btn btn-warning">แก้ใข</a>
        </td>
        <td>
            <form method="post" class="delete_form" action="{{action('MajorController@destroy',$row->major_id)}}">{{csrf_field()}}
                <input type="hidden" name="_method" value="DELETE"/>
                <button type="submit" class="btn btn-danger"  onclick="return confirm('คุณตั้งใจจะลบข้อมูลหรือไม่ ?');">ลบ</button>
            </form>
        </td>
        @endforeach
      </tbody>
    </table>
    <!--end: Datatable-->
  </div>
</div>

@endsection

{{-- Styles Section --}}
@section('styles')

@endsection

{{-- Scripts Section --}}
@section('scripts')

<script src="{{ asset('js/pages/crud/ktdatatable/base/html-table.js') }}" type="text/javascript"></script>

@endsection