routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'PagesController@index')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {

    Route::resource('student', 'StudentController');
    Route::resource('teacher', 'TeacherController');
    Route::resource('employee', 'EmployeeController');
    Route::resource('major', 'MajorController');
    Route::resource('subjectgroup', 'SubjectgroupController', ['names' => 'subjectgroup']);
    Route::resource('groupsubject', 'GroupsubjectController');
    Route::resource('subject', 'SubjectController');
    Route::resource('majortype', 'MajortypeController');
    Route::resource('faculty', 'FacultyController');
    Route::resource('course', 'CourseController');
    Route::resource('classroom', 'ClassroomController');
    Route::resource('lecturer', 'LecturerController');
    Route::resource('educourse', 'EducourseController');

    Route::post('/find/district', 'ProviceController@district')->name('get_district');
    Route::post('/find/subdistrict', 'ProviceController@subdistrict')->name('get_subdistrict');
    Route::post('/find/poscode', 'ProviceController@poscode')->name('get_poscode');
    Route::post('/find/district1', 'ProviceController@district1')->name('get_district1');
    Route::post('/find/subdistrict1', 'ProviceController@subdistrict1')->name('get_subdistrict1');

//  Route::resource('purchase-order', 'PurchaseOrderController');
    //   Route::resource('department', 'DepartmentController');
    //   Route::resource('branch', 'BranchController');
    //   Route::resource('company', 'CompanyController');
});

// Demo routes
Route::get('/datatables', 'PagesController@datatables');
Route::get('/ktdatatables', 'PagesController@ktDatatables');
Route::get('/select2', 'PagesController@select2');
Route::get('/icons/custom-icons', 'PagesController@customIcons');
Route::get('/icons/flaticon', 'PagesController@flaticon');
Route::get('/icons/fontawesome', 'PagesController@fontawesome');
Route::get('/icons/lineawesome', 'PagesController@lineawesome');
Route::get('/icons/socicons', 'PagesController@socicons');
Route::get('/icons/svg', 'PagesController@svg');

// Quick search dummy route to display html elements in search dropdown (header search)
Route::get('/quick-search', 'PagesController@quickSearch')->name('quick-search');

Auth::routes();
Route::get('/home', 'PagesController@index')->name('home');
// Route::get('/home', 'HomeController@index')->name('home');

app/Teacher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Teacher extends Model
{
    protected $table = 'teachers';
    protected $fillable = ['t_ID','t_title','t_Name_th','t_Lname_th','t_Name_en','t_Lname_en','t_img','t_p_ID',
    't_tel','email','religion','blood_type','disability','addr_birthplace','addr_b_t','addr_b_city','addr_b_prov','addr_b_post','addr_cerrent','addr_c_t','addr_c_city',
    'addr_c_prov','addr_c_post','birthday','work_date','date_permit','retire_date','date_permit','retire_date','expertise','major_id','subj_group_id','date_permit',
    'retire_date','expertise','major_id','subj_group_id','mate','father','mother','position','position_exec','degree','university','year'];
}

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use App\TbTeache;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class TeacherController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $page_title = 'ข้อมูลอาจารย์';
        $teacher = TbTeache::get();
        return view('pages.Teacher.index', compact('page_title', 'teacher'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $page_title = 'เพิ่มข้อมูลอาจารย์';
        return view('pages.Teacher.create', compact('page_title'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $uploade = new UploadeFileController();

        if (!empty($request->t_img)) {
            $request->t_img = $uploade->uploadImage(
                $request->t_img,
                'teacher',
                Str::random(5)
            );
        }
        $requestData = $request->all();
        $requestData['t_img'] = $request->t_img;
        TbTeache::create($requestData);
        return redirect()->route('teacher.index')->with('success', 'เพิ่มข้อมูลสำเร็จ');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $page_title = 'แก้ใขข้อมูลอาจารย์';
        $teacher = TbTeache::find($id);
        return view('pages.Teacher.edit', compact('page_title', 'teacher', 'id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $teacher = TbTeache::find($id);
        $teacher->t_ID = $request->get('t_ID');
        $teacher->t_title = $request->get('t_title');
        $teacher->t_Name_th = $request->get('t_Name_th');
        $teacher->t_Lname_th = $request->get('t_Lname_th');
        $teacher->t_Name_en = $request->get('t_Name_en');
        $teacher->t_Lname_en = $request->get('t_Lname_en');
        $teacher->t_p_ID = $request->get('t_p_ID');
        $teacher->t_tel = $request->get('t_tel');
        $teacher->email = $request->get('email');
        $teacher->blood_type = $request->get('blood_type');
        $teacher->disability = $request->get('disability');
        $teacher->addr_birthplace = $request->get('addr_birthplace');
        $teacher->addr_b_t = $request->get('addr_b_t');
        $teacher->addr_b_city = $request->get('addr_b_city');
        $teacher->addr_b_prov = $request->get('addr_b_prov');
        $teacher->addr_b_post = $request->get('addr_b_post');
        $teacher->addr_cerrent = $request->get('addr_cerrent');
        $teacher->addr_c_t = $request->get('addr_c_t');
        $teacher->addr_c_city = $request->get('addr_c_city');
        $teacher->addr_c_prov = $request->get('addr_c_prov');
        $teacher->addr_c_post = $request->get('addr_c_post');
        $teacher->birthday = $request->get('birthday');
        $teacher->work_date = $request->get('work_date');
        $teacher->date_permit = $request->get('date_permit');
        $teacher->retire_date = $request->get('retire_date');
        $teacher->major_id = $request->get('major_id');
        $teacher->subj_group_id = $request->get('subj_group_id');
        $teacher->mate = $request->get('mate');
        $teacher->father = $request->get('father');
        $teacher->mother = $request->get('mother');
        $teacher->position = $request->get('position');
        $teacher->position_exec = $request->get('position_exec');
        $teacher->degree = $request->get('degree');
        $teacher->university = $request->get('university');
        $teacher->year = $request->get('year');
        $teacher->save();
        return redirect()->route('teacher.index')->with('success', 'อัพเดตเรียบร้อย');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $teacher = TbTeache::find($id);
        $teacher->delete();
        return redirect()->route('teacher.index')->with('success', 'ลบข้อมูลเรียบร้อย');
    }
}

resources/views/pages/Teacher/index.blade.php
{{-- Extends layout --}}
@extends('layout.default')

{{-- Content --}}
@section('content')

<div class="card card-custom">
  <div class="card-header flex-wrap border-0 pt-6 pb-0">
    <div class="card-title">
      <h2 class="card-label">ข้อมูลอาจารย์
        <div class="text-muted pt-2 font-size-sm"></div>
      </h2>
    </div>
    <div class="card-toolbar">
      <!--begin::Button-->
      <a href="{{route('teacher.create')}}" class="btn btn-primary font-weight-bolder">
        <span class="svg-icon svg-icon-md">
          <!--begin::Svg Icon | path:assets/media/svg/icons/Design/Flatten.svg-->
          <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
              <rect x="0" y="0" width="24" height="24" />
              <circle fill="#000000" cx="9" cy="15" r="6" />
              <path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3" />
            </g>
          </svg>
          <!--end::Svg Icon-->
        </span>เพิ่มข้อมูลอาจารย์</a>
      <!--end::Button-->
    </div>
  </div>
  <div class="card-body">
    <!--begin: Search Form-->
    <!--begin::Search Form-->
    <div class="mb-7">
      <div class="row align-items-center">
        <div class="col-lg-9 col-xl-8">
          <div class="row align-items-center">
            <div class="col-md-4 my-2 my-md-0">
              <div class="input-icon">
                <input type="text" class="form-control" placeholder="Search..." id="kt_datatable_search_query" />
                <span>
                  <i class="flaticon2-search-1 text-muted"></i>
                </span>
              </div>
            </div>
            <div class="col-md-4 my-2 my-md-0">
              <div class="d-flex align-items-center">
                <label class="mr-3 mb-0 d-none d-md-block">Status:</label>
                <select class="form-control" id="kt_datatable_search_status">
                  <option value="">All</option>
                  <option value="1">Active</option>
                  <option value="2">Inactive</option>
                </select>
              </div>
            </div>

          </div>
        </div>
        <div class="col-lg-3 col-xl-4 mt-5 mt-lg-0">
          <a href="#" class="btn btn-light-primary px-6 font-weight-bold">Search</a>
        </div>
      </div>
    </div>
    <!--end::Search Form-->
    <!--end: Search Form-->
    <!--begin: Datatable-->
    @if ($message = Session::get('success'))
    <div class="alert alert-success">
      <p>{{ $message }}</p>
    </div>
    @endif
    <table class="datatable datatable-bordered datatable-head-custom" id="kt_datatable">
      <thead>
        <tr>
          <th title="Field #1">รหัสอาจารย์</th>
          <th title="Field #2">ชื่อ-สกุล</th>
          <th title="Field #2">อีเมล์</th>
          <th title="Field #2">เลขบัตรประชาชน</th>
          <th title="Field #4">option</th>
          <th title="Field #5"></th>
        </tr>
      </thead>
      <tbody>
        @foreach ($teacher as $row)
        <tr>
        <td>{{$row->t_ID}}</td>
        <td>{{$row->t_Name_th}}  {{$row->t_Lname_th}}</td>
        <td>{{$row->email}}</td>
        <td>{{$row->t_p_ID}}</td>

        <td>
        <span class="d-flex" style="width: 500px;/* display: flex; */">
            <a href="{{action('TeacherController@edit',$row->t_ID)}}" class="btn btn-warning ml-2">แก้ใข</a> &nbsp;&nbsp;&nbsp;
            <form method="post" class="delete_form" action="{{action('TeacherController@destroy',$row->t_ID)}}">{{csrf_field()}}
                <input type="hidden" name="_method" value="DELETE"/>
                <button type="submit" class="btn btn-danger"  onclick="return confirm('คุณตั้งใจจะลบข้อมูลหรือไม่ ?');">ลบ</button>
            </form></span>
        </td>
        @endforeach
      </tbody>
    </table>
    <!--end: Datatable-->
  </div>
</div>



@endsection

{{-- Styles Section --}}
@section('styles')

@endsection

{{-- Scripts Section --}}
@section('scripts')

<script src="{{ asset('js/pages/crud/ktdatatable/base/html-table.js') }}" type="text/javascript"></script>


@endsection